# Generated by Django 3.2.5 on 2021-09-20 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venkat_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empoloy',
            old_name='emp_id',
            new_name='deportment',
        ),
    ]
